### PR TITLE
installed isc-dhcp/added dhcp.conf/dynamic addresses

### PR DESCRIPTION
**Pull request by privatereese**
Added isc-dhcp to provision and started it up in bootstrap

created dhcpd.conf file based on agreed configuration basics

missing:

- ~dhcpd.conf autointegration in the vagrant vm~

- ~tftp boot folder structure not yet deployed~

- should get an automated startup script
- will write a documentation (PR: https://github.com/argos-research/documentation/pull/23)

### CODE REVIEW

**Comment by irgendwie** [comment]
I switched base branch from master to 1608 since 1608 is currently our main branch.

**Comment by irgendwie** [comment]
@privatereese please verify
- dhcpd.conf file is now automatically copied before dhcp server is started
- fixed your problem with the Vagrantfile (auto_config is a boolean value, not string!)

**Comment by privatereese** [comment]
this pull request is ready to be merged if no further problems are found. Open topics will be addressed later. @irgendwie

**Review by BugUser0815 — CHANGES_REQUESTED** [review]
@privatereese something seems not right here.
"default: /vagrant/config-data/tftp-folder.sh: 5: /vagrant/config-data/tftp-folder.sh: Syntax error: "(" unexpected"

**Review by BugUser0815 — APPROVED** [review]

**Comment by privatereese** [comment]
@irgendwie Please approve and finally merge PR

**Comment by BugUser0815** [comment]
@privatereese @irgendwie Pandaboard SD card files and dom0-HW's runfile are also updated and tested now.
Works like a charm.

**Review by irgendwie — APPROVED** [review]

**Pull request merged**
